# Generated by Django 3.2.7 on 2021-09-08 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsfbank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='accno',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
