# Generated by Django 3.2.7 on 2021-09-08 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tsfbank', '0002_customers_accno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('transaction_status', models.CharField(default='PENDING', max_length=255)),
                ('debited_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='tsfbank.customers')),
                ('received_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='tsfbank.customers')),
            ],
        ),
    ]
