# Generated by Django 3.2.7 on 2021-09-11 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsfbank', '0003_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='img',
            field=models.ImageField(default=0, upload_to='pics'),
            preserve_default=False,
        ),
    ]
